spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ENC(Gb401MMFyfcMyYKLTj/MmuSyCpDB0D8muH4llyHdVpn3Xh1GIoTfEfUiyjZTgv/QU06GJy6aZLkI7t3S+WoDGg==)
spring.mail.password=jqeq ixlw fnbi prsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Optional: Timeout-Settings
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mail.to=ENC(Gb401MMFyfcMyYKLTj/MmuSyCpDB0D8muH4llyHdVpn3Xh1GIoTfEfUiyjZTgv/QU06GJy6aZLkI7t3S+WoDGg==)